{{- if and .Values.otel.headers (not .Values.otel.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "speedster.fullname" . }}
  labels:
    {{- include "speedster.labels" . | nindent 4 }}
type: Opaque
stringData:
  # OTEL Headers (for authentication)
  OTEL_EXPORTER_OTLP_HEADERS: {{ range $key, $value := .Values.otel.headers }}{{ $key }}={{ $value }},{{ end }}
{{- end }}
